# Generated by Django 6.0.6 on 2026-06-26 12:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('koherent', '0003_rename_assignation_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The identifier of the object. Consult the documentation for the format', max_length=1000)),
                ('object', models.PositiveIntegerField(help_text='The object id of the object, on its associated service')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.client')),
                ('user', models.ForeignKey(help_text='The user that created this csomsment', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Title of the Room', max_length=1000)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this room got created')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this room belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that have pinned the workspace', related_name='pinned_rooms', to=settings.AUTH_USER_MODEL)),
                ('contextual_structures', models.ManyToManyField(to='kammer.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_streaming', models.BooleanField(default=False)),
                ('text', models.TextField(help_text='A clear text representation of the rich comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this comment got created')),
                ('descendants', models.JSONField(default=list, help_text='The immediate descendends of the comments. Think typed Rich Representation')),
                ('adresses', models.ManyToManyField(blank=True, help_text='The users that got mentioned in this comment', related_name='addressed_in', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(help_text='The user that created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='kammer.agent')),
                ('is_reply_to', models.ForeignKey(blank=True, help_text='Is This a reply to a certain comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='kammer.message')),
                ('targets', models.ManyToManyField(help_text='The agents this message targets', related_name='received_messages', to='kammer.agent')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kammer.room')),
                ('attached_structures', models.ManyToManyField(to='kammer.structure')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_streaming', models.BooleanField(default=False)),
                ('text', models.TextField(help_text='A clear text representation of the rich comment')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time this comment got created')),
                ('descendants', models.JSONField(default=list, help_text='The immediate descendends of the comments. Think typed Rich Representation')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created this comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kammer.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='kammer.message')),
                ('is_reply_to', models.ForeignKey(blank=True, db_constraint=False, help_text='Is This a reply to a certain comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kammer.message')),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kammer.room')),
            ],
            options={
                'verbose_name': 'historical message',
                'verbose_name_plural': 'historical messages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='agent',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kammer.room'),
        ),
    ]
