# Generated by Django 5.2 on 2025-05-06 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The identifier of the object. Consult the documentation for the format', max_length=1000)),
                ('object', models.PositiveIntegerField(help_text='The object id of the object, on its associated service')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The Title of the Room', max_length=1000)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that have pinned the workspace', related_name='pinned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentikate.client')),
                ('user', models.ForeignKey(help_text='The user that created this csomsment', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kammer.room')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_streaming', models.BooleanField(default=False)),
                ('text', models.TextField(help_text='A clear text representation of the rich comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this comment got created')),
                ('descendants', models.JSONField(default=list, help_text='The immediate descendends of the comments. Think typed Rich Representation')),
                ('adresses', models.ManyToManyField(blank=True, help_text='The users that got mentioned in this comment', related_name='addressed_in', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(help_text='The user that created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='kammer.agent')),
                ('is_reply_to', models.ForeignKey(blank=True, help_text='Is This a reply to a certain comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='kammer.message')),
                ('targets', models.ManyToManyField(help_text='The agents this message targets', related_name='received_messages', to='kammer.agent')),
                ('attached_structures', models.ManyToManyField(to='kammer.structure')),
            ],
        ),
    ]
