# Generated by Django 6.0.6 on 2026-08-21 06:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kammer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "all_objects",
            },
        ),
        migrations.AlterModelManagers(
            name="room",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
