# Generated by Django 5.2 on 2026-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kammer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contextual_structures',
            field=models.ManyToManyField(to='kammer.structure'),
        ),
    ]
