# Generated by Django 5.2 on 2026-06-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kammer', '0002_room_contextual_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kammer.room'),
            preserve_default=False,
        ),
    ]
