# Generated by Django 6.0.6 on 2026-08-21 06:15

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kammer", "0002_alter_room_options_alter_room_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "all_objects",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "all_objects",
            },
        ),
        migrations.AlterModelManagers(
            name="agent",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="message",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="agent",
            name="user",
            field=models.ForeignKey(
                help_text="The user this agent acts on behalf of",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
