# Generated by Django 6.0.6 on 2026-09-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kammer", "0003_alter_agent_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="room",
            field=models.ForeignKey(
                help_text="The room this agent participates in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to="kammer.room",
            ),
        ),
    ]
