import strawberry
from typing import Annotated, Optional, List
from strawberry.types import Info
from llm import models, enums, filters, scalars as llmscalars
from llm.redaction import redact_config
import strawberry_django
from strawberry import scalars
# --- Strawberry types ---

# --- RETURN TYPES ---


@strawberry.type(description="The type of the tool")
class FunctionCall:
    """A function call for a large language model"""

    name: str
    arguments: str


@strawberry.type(description="A function definition for a large language model")
class ToolCall:
    """A function call for a large language model"""

    id: str
    type: enums.ToolType
    function: FunctionCall


@strawberry.type
class ChatMessage:
    """A chat message input for a large language model"""

    role: enums.Role
    content: Optional[str]
    name: Optional[str] = None
    tool_call_id: Optional[str] = None
    function_call: Optional[FunctionCall] = None
    tool_calls: Optional[List[ToolCall]] = None


@strawberry.type
class ThinkingBlock:
    type: enums.ThinkingBlockType
    thinking: str
    signature: Optional[str] = None


@strawberry.type
class Choice:
    """A choice in the chat response"""

    index: int
    message: ChatMessage
    finish_reason: Optional[str] = None
    thinking_blocks: Optional[List[ThinkingBlock]] = None
    reasoning_content: Optional[str] = None


@strawberry.type
class Usage:
    """The usage of the chat response"""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    prompt_token_details: Optional[scalars.JSON] = None
    completion_token_details: Optional[scalars.JSON] = None


@strawberry.type
class ChatResponse:
    """A chat response from a large language model"""

    id: str
    object: str
    system_fingerprint: str | None = None
    created: int
    model: str
    choices: List[Choice]
    usage: Optional[Usage]


@strawberry.type(description="A generated image, base64 encoded")
class ImageResponse:
    """An image generated by a large language model."""

    image: llmscalars.Base64EncodedString


@strawberry_django.type(models.LLMModel, description="A LLM model to chage with", filters=filters.LLMModelFilter, ordering=filters.LLMModelOrder, pagination=True)
class LLMModel:
    """A large language model."""

    @classmethod
    def get_queryset(cls, queryset, info, **kwargs):
        """Restrict every read of this type to the request's organization.

        strawberry_django runs this once per queryset, on list fields, singular
        fields and nested traversals alike, so scoping lives here rather than in
        each resolver.
        """
        return queryset.filter(provider__organization=info.context.request.organization)

    id: strawberry.ID
    model_id: str
    label: str
    provider: "Provider"

    features: List[enums.FeatureType] = strawberry_django.field(description="The features supported by the model")
    embedder_for: List[Annotated["ChromaCollection", strawberry.lazy("vector.types")]] = strawberry_django.field(description="The collections that can be embedded with this model")
    llm_string: str = strawberry_django.field(description="The string to use for the LLM model")
    input_modalities: list[enums.Modality] = strawberry_django.field(description="The modalities this model accepts as input")
    output_modalities: list[enums.Modality] = strawberry_django.field(description="The modalities this model produces as output")


@strawberry_django.type(models.Provider, description="A provider of LLMs", filters=filters.ProviderFilter, ordering=filters.ProviderOrder, pagination=True)
class Provider:
    """A provider of LLMs."""

    @classmethod
    def get_queryset(cls, queryset, info, **kwargs):
        """Restrict every read of this type to the request's organization."""
        return queryset.filter(organization=info.context.request.organization)

    id: strawberry.ID
    name: str
    api_base: Optional[str]
    models: List[LLMModel]
    kind: enums.ProviderKind = strawberry_django.field(
        description="The kind of the provider",
        default=enums.ProviderKind.UNKNOWN,
    )

    @strawberry_django.field(description="Whether an API key is configured for this provider. The key itself is never exposed.")
    def has_api_key(self) -> bool:
        """Report whether a credential is set, without disclosing it."""
        return bool(self.api_key)

    @strawberry_django.field(description="Provider configuration, with credential-bearing keys redacted.")
    def additional_config(self) -> Optional[scalars.JSON]:
        """Return the extra provider config with anything secret-looking masked.

        ``additional_config`` is a free-form blob that routinely carries tokens
        alongside harmless settings, so it is filtered on the way out rather
        than withheld wholesale.
        """
        return redact_config(self.additional_config)


@strawberry_django.type(models.DefaultUse, description="A default use for a model", filters=filters.DefaultUseFilter, ordering=filters.DefaultUseOrder, pagination=True)
class DefaultUse:
    """A model registered as the default for one kind of task."""

    @classmethod
    def get_queryset(cls, queryset, info, **kwargs):
        """Restrict to the calling user's own defaults in this organization."""
        return queryset.filter(organization=info.context.request.organization, user=info.context.request.user)

    id: strawberry.ID
    model: "LLMModel"
    kind: str
