# Generated by Django 6.0.6 on 2026-08-21 06:01

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
        ("vector", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chromacollection",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "all_objects",
            },
        ),
        migrations.AlterModelManagers(
            name="chromacollection",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="chromacollection",
            name="name",
            field=models.CharField(
                help_text="The human-readable name of the collection, unique within its organization",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="chromacollection",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization this collection belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="authentikate.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chromacollection",
            unique_together={("organization", "name")},
        ),
    ]
