# Generated by Django 5.2 on 2025-08-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_provider_kind'),
        ('vector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromacollection',
            name='embedder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedder_for', to='llm.llmmodel'),
        ),
    ]
