"""
Django settings for mikro_server project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from .configuration import Settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Everything security-relevant comes from the validated config (see
# alpaka_server/configuration.py and CONFIG.md); nothing is hard-coded here.
SECRET_KEY = conf.django.secret_key
DEBUG = conf.django.debug
ALLOWED_HOSTS: list[str] = list(conf.django.hosts)
USE_X_FORWARDED_HOST = conf.django.use_x_forwarded_host
CSRF_TRUSTED_ORIGINS: list[str] = list(conf.django.csrf_trusted_origins)


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels_redis",
    "guardian",
    "simple_history",
    "authentikate",
    "koherent",
    "kante",
    "channels",
    "django_probes",
    "kammer",
    "llm",
    "vector",
    "health_check",  # required for health checks
    "health_check.db",  # stock Django health checkers
]


AUTH_USER_MODEL = "authentikate.User"


CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(conf.redis.host, conf.redis.port)], "prefix": conf.redis.channel_prefix},
    },
}


OLLAMA_URL = conf.ollama_url
CHROMA_DB_HOST = conf.chroma_db_host
CHROMA_DB_PORT = conf.chroma_db_port

CORS_ALLOW_ALL_ORIGINS = True


STRAWBERRY_DJANGO = {
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
    "USE_DEPRECATED_FILTERS": False,
    "DEFAULT_PK_FIELD_NAME": "id",
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "alpaka_server.urls"

# Consumed by kante's ``dynamicpath``/``re_dynamicpath`` (see urls.py and
# kante.router), which prefix every URL pattern themselves because channels'
# URLRouter matches the raw scope["path"]. Deliberately NOT Django's
# FORCE_SCRIPT_NAME: Django would strip the prefix from path_info while the
# patterns still carry it, so nothing would match.
MY_SCRIPT_NAME = conf.django.force_script_name

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # this is default
    "guardian.backends.ObjectPermissionBackend",
)

WSGI_APPLICATION = "alpaka_server.wsgi.application"
ASGI_APPLICATION = "alpaka_server.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Semantic search (the vendored ``embeddings`` package) over the rows users browse: rooms
# (title + description) and Chroma collections (their name + description -- the collection
# *metadata*, not the documents inside, which Chroma embeds with the collection's own LLM
# embedder). A model2vec static model runs in this process (no service, no GPU, ~1 ms per
# row) and fills a pgvector column on save; the filters' ``search`` ORs "cosine distance
# below DISTANCE_THRESHOLD" onto the substring match. DIMENSIONS is also the width of the
# database columns: the ``embeddings`` system checks refuse to start when the model, this
# setting and a column disagree. Rows filled by another model are re-embedded by an
# in-process loop (see ``alpaka_server/asgi.py``), never by a command.
EMBEDDINGS = {
    "ENABLED": conf.embeddings.enabled,
    "MODEL": conf.embeddings.model,
    "MODEL_PATH": conf.embeddings.model_path,
    "DIMENSIONS": conf.embeddings.dimensions,
    "DISTANCE_THRESHOLD": conf.embeddings.distance_threshold,
    "SWEEP_INTERVAL": conf.embeddings.sweep_interval,
    "SWEEP_BATCH_SIZE": conf.embeddings.sweep_batch_size,
}
# The in-process healer that re-embeds stale rows. Off under the test suite, which calls
# ``embeddings.healer.reembed_stale`` directly so a background pass never races an assertion.
EMBEDDINGS_HEALER_ENABLED = True


AUTHENTIKATE = conf.authentikate.model_dump()


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{conf.redis.host}:{conf.redis.port}/1",
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "kluster_server_cache",
    }
}


CACHE_TTL_DEFAULT = 60 * 15


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# WhiteNoise serves static directly from the staticfiles finders at request time
# (works under both runserver and daphne), so no collectstatic / STATIC_ROOT is needed.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


PROVIDER_PARTNERS = [p.model_dump(mode="json") for p in conf.provider_partners]

# Superuser provisioned by ``manage.py ensureadmin`` (run.sh). Stored as a plain
# dict because Django settings only expose UPPERCASE names; the command
# re-validates it, the same way ensurepartners does for PROVIDER_PARTNERS.
DJANGO_ADMIN = conf.django.admin.model_dump() if conf.django.admin else None
