# Generated by Django 5.2 on 2025-10-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0002_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_base', models.URLField(blank=True, null=True)),
                ('additional_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN'), ('openrouter', 'OPENROUTER')], default='unknown', max_length=50)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this provider belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
            ],
            options={
                'unique_together': {('name', 'api_key')},
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.provider')),
            ],
        ),
    ]
