# Generated by Django 6.0.6 on 2026-06-26 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('identifier', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('short_description', models.CharField(blank=True, max_length=280, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('kind', models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN'), ('openrouter', 'OPENROUTER')], default='unknown', max_length=50)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_base', models.URLField(blank=True, null=True)),
                ('additional_config', models.JSONField(blank=True, null=True)),
                ('auto_configure', models.BooleanField(default=False, help_text='If set, a Provider is created for every new organization.')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Filter conditions to determine which users/organizations this partner applies to. Example: {'email_domain_equals': ['example.com'], 'email_domain_ends_with': ['edu']}", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_base', models.URLField(blank=True, null=True)),
                ('additional_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN'), ('openrouter', 'OPENROUTER')], default='unknown', max_length=50)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this provider belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('partner', models.ForeignKey(blank=True, help_text='The partner this provider was auto-provisioned from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_providers', to='llm.providerpartner')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('input_modalities', models.JSONField(blank=True, default=list, null=True)),
                ('output_modalities', models.JSONField(blank=True, default=list, null=True)),
                ('pinned_by', models.ManyToManyField(related_name='pinned_models', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.provider')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=600)),
                ('organization', models.ForeignKey(help_text='The organization this provider belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('user', models.ForeignKey(help_text='The organization this provider belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.llmmodel')),
            ],
            options={
                'unique_together': {('kind', 'organization', 'user')},
            },
        ),
    ]
