# Generated by Django 5.2 on 2025-11-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0002_membership'),
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DefaultUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=600)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.llmmodel')),
                ('organization', models.ForeignKey(help_text='The organization this provider belongs to', on_delete=django.db.models.deletion.CASCADE, to='authentikate.organization')),
                ('user', models.ForeignKey(help_text='The organization this provider belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
