# Generated by Django 6.0.6 on 2026-09-10 15:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('llm', '0002_alter_defaultuse_options_alter_llmmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'DAY'), ('week', 'WEEK'), ('month', 'MONTH')], default='month', max_length=8)),
                ('limit_tokens', models.PositiveBigIntegerField(blank=True, help_text='Maximum total tokens per period', null=True)),
                ('limit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum cost in USD per period', max_digits=16, null=True)),
                ('hard', models.BooleanField(default=True, help_text='Block calls once exceeded; otherwise only log a warning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, help_text='Restrict the budget to one model; null applies to every model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='llm.llmmodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='authentikate.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Restrict the budget to one user; null applies to everyone in the organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_kind', models.CharField(blank=True, default='', max_length=50)),
                ('model_identifier', models.CharField(blank=True, default='', help_text='The provider-side model id at the time of the call', max_length=255)),
                ('llm_string', models.CharField(blank=True, default='', max_length=512)),
                ('endpoint', models.CharField(choices=[('graphql_chat', 'GRAPHQL_CHAT'), ('graphql_image', 'GRAPHQL_IMAGE'), ('rest_chat', 'REST_CHAT'), ('rest_completion', 'REST_COMPLETION'), ('rest_embedding', 'REST_EMBEDDING'), ('vector_embedding', 'VECTOR_EMBEDDING')], max_length=32)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=10, help_text='Cost in USD as reported or estimated by litellm; null when the model is not in its price map', max_digits=20, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'ERROR')], default='ok', max_length=8)),
                ('error_type', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='The client the call came through', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='authentikate.client')),
                ('model', models.ForeignKey(blank=True, help_text='The model that was called, if it still exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='llm.llmmodel')),
                ('organization', models.ForeignKey(help_text='The organization that was billed', on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='authentikate.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The user who made the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='llm_usage_org_created_idx'), models.Index(fields=['organization', 'user', 'created_at'], name='llm_usage_org_user_created_idx')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
