# Generated by Django 5.2 on 2025-11-20 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0002_membership'),
        ('llm', '0002_llmmodel_pinned_by_defaultuse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultuse',
            unique_together={('kind', 'organization', 'user')},
        ),
    ]
