# Generated by Django 5.2 on 2025-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_provider_created_at_provider_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
