# Generated by Django 6.0.6 on 2026-09-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_budget_usagerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagerecord",
            name="status",
            field=models.CharField(
                choices=[("ok", "OK"), ("error", "ERROR"), ("aborted", "ABORTED")],
                default="ok",
                max_length=8,
            ),
        ),
    ]
