# Generated by Django 5.2 on 2025-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_llmmodel_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='kind',
            field=models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN')], default='unknown', max_length=50),
        ),
    ]
