# Generated by Django 5.2 on 2025-11-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_defaultuse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='input_modalities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='output_modalities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
