# Generated by Django 6.0.6 on 2026-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_alter_usagerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='kind',
            field=models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN'), ('openrouter', 'OPENROUTER'), ('typesafe', 'TYPESAFE'), ('ollaya', 'OLLAYA')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='providerpartner',
            name='kind',
            field=models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN'), ('openrouter', 'OPENROUTER'), ('typesafe', 'TYPESAFE'), ('ollaya', 'OLLAYA')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='endpoint',
            field=models.CharField(choices=[('graphql_chat', 'GRAPHQL_CHAT'), ('graphql_image', 'GRAPHQL_IMAGE'), ('rest_chat', 'REST_CHAT'), ('rest_completion', 'REST_COMPLETION'), ('rest_embedding', 'REST_EMBEDDING'), ('vector_embedding', 'VECTOR_EMBEDDING'), ('graphql_decide', 'GRAPHQL_DECIDE'), ('rest_decide', 'REST_DECIDE')], max_length=32),
        ),
    ]
