# Generated by Django 6.0.6 on 2026-06-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('llm', '0004_llmmodel_input_modalities_llmmodel_output_modalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('identifier', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('short_description', models.CharField(blank=True, max_length=280, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('kind', models.CharField(choices=[('openai', 'OPENAI'), ('anthropic', 'ANTHROPIC'), ('google', 'GOOGLE'), ('cohere', 'COHERE'), ('mistral', 'MISTRAL'), ('huggingface', 'HUGGINGFACE'), ('ollama', 'OLLAMA'), ('azure', 'AZURE'), ('aws', 'AWS'), ('vertex_ai', 'VERTEX_AI'), ('palm', 'PALM'), ('replicate', 'REPLICATE'), ('together_ai', 'TOGETHER_AI'), ('anyscale', 'ANYSCALE'), ('fireworks_ai', 'FIREWORKS_AI'), ('deepinfra', 'DEEPINFRA'), ('perplexity', 'PERPLEXITY'), ('groq', 'GROQ'), ('custom', 'CUSTOM'), ('unknown', 'UNKNOWN'), ('openrouter', 'OPENROUTER')], default='unknown', max_length=50)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_base', models.URLField(blank=True, null=True)),
                ('additional_config', models.JSONField(blank=True, null=True)),
                ('auto_configure', models.BooleanField(default=False, help_text='If set, a Provider is created for every new organization.')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text="Filter conditions to determine which users/organizations this partner applies to. Example: {'email_domain_equals': ['example.com'], 'email_domain_ends_with': ['edu']}", null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('organization', 'name')},
        ),
        migrations.AddField(
            model_name='provider',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='The partner this provider was auto-provisioned from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_providers', to='llm.providerpartner'),
        ),
    ]
